### ISSUE TITLE
Problèmes actuels

### ISSUE THREAD

**Issue by youatik** [youatik/FibonacciSequence#1]
Dans le programme actuel, seul le nième nombre de Fibonacci est affiché. Cependant, pour afficher la séquence complète jusqu'au nième nombre, des ajustements supplémentaires doivent être apportés au code. Il faudrait mettre à jour le programme pour stocker chaque nombre de Fibonacci calculé dans une structure de données appropriée, telle qu'une liste ou un tableau, puis afficher la séquence complète plutôt que seulement le nième nombre.
De plus, dans le contexte du calcul récursif des nombres de Fibonacci, un débordement peut se produire lorsque la valeur calculée dépasse la plage de représentation du type de données utilisé. Cela peut entraîner des résultats inattendus, tels que le passage d'une valeur maximale à une valeur négative ou l'omission de bits significatifs au-delà de la capacité du type de données.
Le programme GUI ne donne pas des temps consistants, probablement en raison de la manière de gérer les "threads".

**Comment by Moti-Velz** [comment]
Gestion des classe d'équivalence à l'entrée afin de gérer les exceptions implémenté.
Ajustement des algorithmes d'exécution
Refactorisation
